### ISSUE TITLE
Sites created an hour ago have no measurments

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#20] opened 2016-10-24 14:19 UTC
On he organization Mubuku, 3 sites created this afternoon, the measurments which were taken are not visible suddenly on the app. They were not uploaded and now they're simply not there. The sites are: 
- Division 11 Lateral
- Division 8 Lateral
- Main canal -P2

**Comment by luethi** [comment] 2016-10-24 14:37
ups, this is not good. I copy this ticket to the internal channel directly to Ranko.

**Comment by rmunk** [comment] 2016-10-25 09:16
Hmm, that is indeed strange. Are you sure you are logged in as the same user and have picked right organization in the sliding menu? Or did you maybe move this sites to different organization or did anything else unordinary.

Can you please send me **discharge.db** file from your phone. It is located in:
/Android/data/ch.photrack.discharge/files

You can also check if recorded movies are still present in the Movies folder there.

**Comment by phanosh** [comment] 2016-10-25 09:38
Yes, user was still logged in. The sites and their geometry info is still there, in the correct organizations but the videos are no longer on the phone. 
Something important: we had no connection on the field so i tried to upload a measurement when i got access to wifi. I got a notification that the site has to be uppoded first. Then, after clicking on te upload button i went to the "examine data" window, which said there are no measurements. So basically, it seems that uploading the site seems to overwrite the measurments

**Comment by phanosh** [comment] 2016-10-25 09:38
I will send the discharge.db file tonight

**Comment by phanosh** [comment] 2016-10-25 10:05
Ok so here's an update. It seems to be a problem of the prticular phone (oppo). Sometimes it bugs and the application crushes. Then you are asked to login again, and measurments are lost again. It usually crushes while processing videos.

**Comment by rmunk** [comment] 2016-10-25 10:21
Can you tell me which phone exactly it is and which username. Maybe I have crash reports on our server if he managed to get online afterwards.

**Comment by phanosh** [comment] 2016-10-25 10:28
The phone is Oppo A33f. The user is Phanos Hadjikyriakou

**Comment by phanosh** [comment] 2016-10-25 13:56
[discharge.zip](https://github.com/luethi/Discharge_Optical_Measurement/files/550762/discharge.zip)

**Comment by rmunk** [comment] 2016-10-25 15:15
I can see only two measurements for site Division 12 Lateral in the database. Did you make this two measurements on Division 12 after the incident? I am really puzzled here as I tried to reproduce this issue on my phone but with no luck. Also I can't find anything in the code that could delete those measurements.

I also cannot find any crash logs from your account on this phone (I have some reports from other users for this phone model). Which means that they somehow got lost. I presume that on this phone somehow when the app crashes all app data gets deleted by the Android system. That would explain why you have to log in again afterwards and why I don't see any crash reports here. And also the database with all measurements would be gone too as well as recorded movies.

**Comment by bosnjak** [comment] 2016-11-03 09:11
Hi @phanosh! Can you please see if you can consistently reproduce this issue? If you can write down the exact steps which will reproduce this in most cases on this phone, we will be able to debug it on our side. Thanks!

**Comment by phanosh** [comment] 2016-11-03 09:15
hi @bosnj , I unfortunately cannot do this now as we gave Beat the phones with measurements. From the field experience, we had this issue several times so I'm not sure there is a procedure to reproduce the issue. I will nevertheless try to find an android phone lying around and try it again.

**Comment by bosnjak** [comment] 2016-11-03 09:17
@phanosh thank you for the quick answer!
@luethi maybe you can try to reproduce this consistently on the Oppo phone?

**Comment by bosnjak** [comment] 2016-11-07 11:44
@phanosh did you talk internally with @luethi about this? I wonder why you are closing it, is the issue not reproducible, or?

**Comment by phanosh** [comment] 2016-11-07 11:46
@bosnj : Sorry, I thought this was transferred to Asana

**Comment by bosnjak** [comment] 2016-11-07 11:52
@phanosh: I don't think if it is, but I might be wrong. In any case, we should refer to the new tickets before closing here, so we can trace the steps to the latest ticket. Just provide a link to the new ticket and close. 
On topic, I'd like to verify this behavior and try to reproduce on the same phone. So either @luethi or whoever has access to the phone model in question.

**Comment by phanosh** [comment] 2016-11-07 11:54
Noted. we don't have any of the phones at hydrosolutions

**Comment by bosnjak** [comment] 2016-11-07 11:56
I thought you brought the phones back with you to CH. They are all at Photrack then?

**Comment by phanosh** [comment] 2016-11-07 12:06
yes, we gave them to @luethi

**Comment by bosnjak** [comment] 2017-02-20 15:54
Since there was no activity on this for a few months, can we close?
cc @luethi @phanosh

**Comment by bosnjak** [comment] 2017-03-29 12:46
ping @luethi

**Closed as completed** 2018-02-20 14:07 UTC
